name: gen_music
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.20.2
  # For server
  - flask=1.1.2
  # Development dependencies
  - black=19.10b0
  - pylint=2.7.4
  - pytest=6.2.3
  - pip=21.0
  - pip:
    # For communicating using Open Sound Control (OSC)
    - python-osc==1.7.6
